% Compile Nitrogen Files.
{ './mhive.erl', [
	{ i, "./nitrogen/include" },
	{ i, "./" },
	{ outdir, "./ebin" }
]}.
{ './core/*', [
	{ i, "./" },
	{ i, "./include" },
	{ outdir, "./ebin" },
	debug_info
]}.
{ './lib/*', [
	{ outdir, "./ebin" }
]}.
{ './web/*', [
	{ i, "./nitrogen/include" },
	{ outdir, "./ebin" },
	debug_info
]}.
{ './test/test.erl', [
	{ i, "./nitrogen/include" },
	{ outdir, "./ebin" },
	debug_info
]}.
