{
    "tasks":[
	{"name":"EncodingTask","encodingtask.src":"/Volumes/Movies/20070404 1515 - PREMIERE 3 - Carlito's Way - Weg zur Macht (Carlito's Way_ Rise to Power).ts","encodingtask.profile":"3e74a312-47b9-4082-a70c-e931f9d84ebd"},
	{"name":"ExportTask","exporttask.jobid":"global/collect","exporttask.format":"mp4","exporttask.trg":"/tmp/test6.mp4","exporttask.overwrite":true},
	{"name":"UploadTask","uploadtask.src":"","uploadtask.trg":""}
    ]
}