{
    "tasks":[
	{"name":"InputTask","uid":"1"},
	{"name":"EncodingTask","uid":"2"},
	{"name":"EncodingTask","uid":"3"},
	{"name":"OutputTask","uid":"4"}
    ],
    "links":[
	{"uid":"1", "linksToUid":"2"},
	{"uid":"1", "linksToUid":"3"},
	{"uid":"2", "linksToUid":"4"},
	{"uid":"3", "linksToUid":"4"}
    ],
    "positions":[
	{"uid":"1", "x":"200", "y":"200"},
	{"uid":"2", "x":"300", "y":"250"},
	{"uid":"3", "x":"300", "y":"350"},
	{"uid":"4", "x":"400", "y":"300"}
    ]
}
