// Code generated by protoc-gen-go from "test.proto"
// DO NOT EDIT!

package ffmpeg

import proto "goprotobuf.googlecode.com/hg/proto"
import "math"
import "os"

// Reference proto, math & os imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf
var _ os.Error

func init() {
}
